# Generated by Django 3.2.9 on 2021-11-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at ...')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
        ),
    ]
