# Generated by Django 3.2.9 on 2021-11-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported', models.BooleanField(default=True)),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('product', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('inventory', models.IntegerField(verbose_name='current_inventory')),
                ('minimum_inventory', models.IntegerField(default=0, verbose_name='minimum_inventory')),
            ],
            options={
                'ordering': ('product',),
            },
        ),
    ]
